In [ ]:
import pandas as pd
df = pd.read_csv("Cars93.csv")
df.tail()

FileNotFoundError: [Errno 2] No such file or directory: 'Cars93.csv'

In [ ]:
def handle_missing_values_alternative(df):
    # Create a copy of the dataframe
    df_copy = df.copy()

    for col in df_copy.select_dtypes(include=['float64', 'int64']).columns:
        df_copy[col] = df_copy[col].fillna(df_copy[col].median())

    for col in df_copy.select_dtypes(include=['object']).columns:
        df_copy[col] = df_copy[col].fillna('Unknown')

    return df_copy

# Usage
df = handle_missing_values_alternative(df)

df.tail()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin
88,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,Unknown,Front,...,21.1,7,187,115,72,38,34.0,14.0,3960,non-USA
89,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,Unknown,Front,...,18.5,5,180,103,67,35,31.5,14.0,2985,non-USA
90,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,Unknown,Front,...,18.5,4,159,97,66,36,26.0,15.0,2810,non-USA
91,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,Rear,...,15.8,5,190,104,67,37,29.5,14.0,2985,non-USA
92,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,Front,...,19.3,5,184,105,69,38,30.0,15.0,3245,non-USA

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
 # Rounding numeric columns to 2 decimal places

def reduce_noise(df):
    for col in df.select_dtypes(include=['float64', 'int64']).columns:
        df[col] = df[col].round(2)
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = df[col].str.strip().str.lower()

    return df

df= reduce_noise(df)
df.tail()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin
88,volkswagen,eurovan,van,16.6,19.7,22.7,17,21,unknown,front,...,21.1,7,187,115,72,38,34.0,14.0,3960,non-usa
89,volkswagen,passat,compact,17.6,20.0,22.4,21,30,unknown,front,...,18.5,5,180,103,67,35,31.5,14.0,2985,non-usa
90,volkswagen,corrado,sporty,22.9,23.3,23.7,18,25,unknown,front,...,18.5,4,159,97,66,36,26.0,15.0,2810,non-usa
91,volvo,240,compact,21.8,22.7,23.5,21,28,driver only,rear,...,15.8,5,190,104,67,37,29.5,14.0,2985,non-usa
92,volvo,850,midsize,24.8,26.7,28.5,20,28,driver & passenger,front,...,19.3,5,184,105,69,38,30.0,15.0,3245,non-usa

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Convert Categorial value to Numerical value
def encode_categorical_features(df):
    label_encoders = {}
    for col in df.select_dtypes(include=['object']).columns:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        label_encoders[col] = le
    return df, label_encoders

encoded_data, encoders = encode_categorical_features(df)

df.tail()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin
88,30,41,5,16.6,19.7,22.7,17,21,2,1,...,21.1,7,187,115,72,38,34.0,14.0,3960,0
89,30,64,0,17.6,20.0,22.4,21,30,2,1,...,18.5,5,180,103,67,35,31.5,14.0,2985,0
90,30,28,4,22.9,23.3,23.7,18,25,2,1,...,18.5,4,159,97,66,36,26.0,15.0,2810,0
91,31,2,0,21.8,22.7,23.5,21,28,1,2,...,15.8,5,190,104,67,37,29.5,14.0,2985,0
92,31,7,2,24.8,26.7,28.5,20,28,0,1,...,19.3,5,184,105,69,38,30.0,15.0,3245,0

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Convert Categorial value to Numerical value
def encode_categorical_features(df):
    label_encoders = {}
    for col in df.select_dtypes(include=['object']).columns:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        label_encoders[col] = le
    return df, label_encoders

encoded_data, encoders = encode_categorical_features(df)

df.tail()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin
88,30,41,5,16.6,19.7,22.7,17,21,2,1,...,21.1,7,187,115,72,38,34.0,14.0,3960,0
89,30,64,0,17.6,20.0,22.4,21,30,2,1,...,18.5,5,180,103,67,35,31.5,14.0,2985,0
90,30,28,4,22.9,23.3,23.7,18,25,2,1,...,18.5,4,159,97,66,36,26.0,15.0,2810,0
91,31,2,0,21.8,22.7,23.5,21,28,1,2,...,15.8,5,190,104,67,37,29.5,14.0,2985,0
92,31,7,2,24.8,26.7,28.5,20,28,0,1,...,19.3,5,184,105,69,38,30.0,15.0,3245,0

In [ ]:
from sklearn.model_selection import train_test_split

def split_data(df, train_ratio=0.7, validation_ratio=0.2, test_ratio=0.1):
    train_data, temp_data = train_test_split(df, test_size=(1 - train_ratio), random_state=42)
    validation_data, test_data = train_test_split(temp_data, test_size=(test_ratio / (test_ratio + validation_ratio)), random_state=42)
    return train_data, validation_data, test_data


train_data, validation_data, test_data = split_data(df)

train_data

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin
31,10,40,3,8.4,10.1,11.9,23,30,2,1,...,13.2,5,171,98,67,36,28.0,12.0,2530,1
77,25,9,0,20.3,28.7,37.1,20,26,1,1,...,18.0,5,184,99,67,37,26.5,14.0,2775,0
9,4,34,1,33.0,34.7,36.3,16,25,1,1,...,18.0,6,206,114,73,43,35.0,18.0,3620,1
70,22,37,1,19.5,20.7,21.9,19,28,1,1,...,18.0,6,201,111,74,42,31.5,17.0,3470,1
5,3,23,2,14.2,15.7,17.3,22,31,1,1,...,16.4,6,189,105,69,41,28.0,16.0,2880,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,7,51,0,14.5,15.8,17.1,23,28,0,1,...,16.0,6,183,104,68,41,30.5,14.0,3085,1
60,19,31,2,14.9,14.9,14.9,19,26,2,2,...,18.0,5,199,113,73,38,28.0,15.0,3610,1
71,23,50,4,11.4,14.4,17.4,23,30,2,0,...,15.9,4,173,97,67,39,24.5,8.0,2640,1
14,5,57,2,13.4,15.9,18.4,21,29,2,1,...,16.5,6,198,108,71,40,28.5,16.0,3195,1
51,16,91,1,34.4,36.1,37.8,18,26,0,2,...,20.0,6,219,117,77,45,31.5,22.0,4055,1

In [ ]:
validation_data

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin
4,2,5,2,23.7,30.0,36.2,22,30,1,2,...,21.1,4,186,109,69,39,27.0,13.0,3640,0
22,8,25,3,7.9,9.2,10.6,29,33,2,1,...,13.2,5,174,98,66,32,26.5,11.0,2270,1
0,0,48,3,12.9,15.9,18.8,25,31,2,1,...,13.2,5,177,102,68,37,26.5,11.0,2705,0
26,8,36,2,14.8,15.6,16.4,21,27,1,1,...,16.0,6,192,105,69,42,30.5,16.0,3080,1
55,17,62,5,16.6,19.1,21.7,18,24,2,0,...,19.6,7,190,110,72,39,27.5,14.0,3735,0
18,5,30,4,34.6,38.0,41.5,17,25,1,2,...,20.0,2,179,96,74,43,27.5,14.0,3380,1
30,10,43,3,6.9,7.4,7.9,31,33,2,1,...,10.0,4,141,90,63,33,26.0,12.0,1845,1
72,24,54,3,8.2,9.0,9.9,31,41,2,1,...,13.2,4,177,99,66,35,25.5,17.0,2350,1
66,21,59,2,21.0,21.5,22.0,21,26,1,1,...,18.5,5,188,104,69,41,28.5,14.0,3200,0
33,10,63,4,10.8,15.9,21.0,22,29,1,2,...,15.4,4,180,101,68,40,24.0,12.0,2850,1
49,15,74,2,34.7,35.2,35.6,18,23,0,2,...,20.6,4,191,106,71,39,25.0,9.0,3515,0
69,22,79,5,19.5,19.5,19.5,18,23,2,1,...,20.0,7,194,110,74,44,30.5,14.0,3715,1
15,5,58,5,14.7,16.3,18.0,18,23,2,1,...,20.0,7,178,110,74,44,30.5,14.0,3715,1
67,22,11,0,13.0,13.5,14.0,24,31,2,1,...,15.2,5,188,103,67,39,28.0,14.0,2910,1
83,29,90,3,7.8,9.8,11.8,32,37,1,1,...,11.9,5,162,94,65,36,24.0,11.0,2055,0
12,5,29,0,11.4,11.4,11.4,25,34,1,1,...,15.6,5,184,103,68,39,26.0,14.0,2785,1
65,21,70,5,16.7,19.1,21.5,17,23,2,1,...,20.0,7,190,112,74,41,27.0,14.0,4100,0
39,11,84,4,11.5,12.5,13.5,30,36,1,1,...,12.4,4,164,97,67,37,24.5,11.0,2475,0

In [ ]:
test_data

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin
44,13,38,3,9.0,10.0,11.0,22,29,2,1,...,13.7,5,172,98,66,36,28.0,12.0,2620,0
11,5,21,0,8.5,13.4,18.3,25,36,2,1,...,15.2,5,182,101,66,38,25.0,13.0,2490,1
10,4,77,2,37.5,40.1,42.7,16,25,0,1,...,20.0,5,204,111,74,44,31.0,14.0,3935,1
68,22,33,2,14.2,16.3,18.4,23,31,1,1,...,16.5,5,190,105,70,42,28.0,16.0,2890,1
40,12,65,4,17.0,19.8,22.7,24,31,0,1,...,15.9,4,175,100,70,39,23.5,8.0,2865,0
90,30,28,4,22.9,23.3,23.7,18,25,2,1,...,18.5,4,159,97,66,36,26.0,15.0,2810,0
28,9,85,3,7.9,12.2,16.5,29,33,2,1,...,13.2,5,174,98,66,36,26.5,11.0,2295,1
78,26,80,3,9.2,11.1,12.9,28,38,1,1,...,12.8,5,176,102,68,40,26.5,12.0,2495,1
35,10,12,5,14.5,19.9,25.3,15,20,1,0,...,21.0,7,176,119,72,45,30.0,14.0,3735,1
62,20,35,2,22.4,26.1,29.9,18,24,1,1,...,19.0,5,190,107,70,43,27.5,14.0,3730,0